# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: hi31145227@aliyun.com  
        password: '!it9s2cu'
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy  --platform linux/amd64 docker://gpustack/gpustack docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/gpustacka:latest-arm64
        #skopeo copy docker://hub.zentao.net/app/zentao:18.13 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/zentao:18.13
        #skopeo copy docker://mariadb:10.6 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/mariadb:10.6
        #skopeo copy docker://langgenius/dify-api:0.15.2 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/dify-api:0.15.2
        #skopeo copy docker://langgenius/dify-web:0.15.2 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/dify-web:0.15.2
        #skopeo copy docker://postgres:15-alpine docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/postgres:15-alpine
        #skopeo copy docker://redis:6-alpine docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/redis:6-alpine
        #skopeo copy docker://langgenius/dify-sandbox:0.2.10 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/dify-sandbox:0.2.10
        #skopeo copy docker://ubuntu/squid:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/squid:latest
        #skopeo copy docker://certbot/certbot docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/certbot
        #skopeo copy docker://nginx:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/nginx:latest
        #skopeo copy docker://pingcap/tidb:v8.4.0 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/tidb:v8.4.0
        #skopeo copy docker://semitechnologies/weaviate:1.19.0 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/weaviate:1.19.0
        #skopeo copy docker://langgenius/qdrant:v1.7.3 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/qdrant:v1.7.3
        #skopeo copy docker://pgvector/pgvector:pg16 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/pgvector:pg16
        #skopeo copy docker://tensorchord/pgvecto-rs:pg16-v0.3.0 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/pgvecto-rs:pg16-v0.3.0
        #skopeo copy docker://ghcr.io/chroma-core/chroma:0.5.20 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/chroma:0.5.20
        #skopeo copy docker://pgvector/pgvector:pg16 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/pgvector:pg16
        #skopeo copy docker://quay.io/oceanbase/oceanbase-ce:4.3.3.0-100000142024101215 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/oceanbase-ce:4.3.3.0-100000142024101215
        #skopeo copy docker://container-registry.oracle.com/database/free:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/free:latest
        #skopeo copy docker://quay.io/coreos/etcd:v3.5.5 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/etcd:v3.5.5
        #skopeo copy docker://minio/minio:RELEASE.2023-03-20T20-16-18Z docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/minio:RELEASE.2023-03-20T20-16-18Z
        #skopeo copy docker://milvusdb/milvus:v2.5.0-beta docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/milvus:v2.5.0-beta
        
        #skopeo copy docker://opensearchproject/opensearch:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/opensearch:latest
        #skopeo copy docker://opensearchproject/opensearch-dashboards:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/opensearch-dashboards:latest
        #skopeo copy docker://mcr.microsoft.com/mssql/server:2022-latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/mssql-server:2022-latest
        #skopeo copy docker://hub.zentao.net/app/zentao:21.2 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/zentao:21.2
        #skopeo copy docker://docker:dind docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/docker:dind
        #skopeo copy docker://gitlab/gitlab-ce:15.11.13-ce.0 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/gitlab-ce:15.11.13-ce.0
        #skopeo copy docker://myscale/myscaledb:1.6.4 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/myscaledb:1.6.4
        #skopeo copy docker://docker.elastic.co/elasticsearch/elasticsearch:8.14.3 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/elasticsearch:8.14.3
        #skopeo copy docker://docker.elastic.co/kibana/kibana:8.14.3 docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/kibana:8.14.3
        #skopeo copy docker://downloads.unstructured.io/unstructured-io/unstructured-api:latest docker://registry.cn-hangzhou.aliyuncs.com/pit_mall/unstructured-api:latest

